### ISSUE TITLE
Ov3rCross enhancement request - constant output selection if no trigger input

### ISSUE THREAD

**Issue by DaveBenham** [gwygonik/acModules#1]
It would be a nice feature if the CV In could continuously select the output if there is no Trigger input patched.

**Comment by gwygonik** [comment]
I had considered this, but was torn about what to do with the trigger output in this scenario... should it trigger when the zone changes based on CV or should it not trigger at all (is it necessary in this mode)? Thoughts?

**Comment by gwygonik** [comment]
I guess I should clarify. The existing module _does_ route the CV to the correct output without a trigger, it just doesn't send a trigger out (when not in S&H mode). So it kind-of boils down to what to do with the trigger. My current thinking is that the trigger outputs when the CV-controlled zone changes AND/OR when an trigger is input (the "AND/OR" being configurable).

**Comment by DaveBenham** [comment]
Ah, cool. So far I have only read the documentation, and I was not able to discern that. Sounds like you have a good design, but the doc implies you need a trigger. You might want to change that.

**Comment by gwygonik** [comment]
Good call - it does read that way. And honestly I forgot it only requires the trigger for outputting a trigger. But I just changed the module's code to have an optional trigger out when not in S&H mode (since _that_ requires a trigger). I'll also update the docs. Thanks!

**Comment by gwygonik** [comment]
2.0.2 got released today which adds the trigger out option when a zone changes, and I updated the docs to reflect the always-output nature of the CV in. I'm not 100% satisfied that the docs are good enough, but will keep tinkering with them. Thanks for reporting this!
